CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'customer',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_code VARCHAR(50) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    company VARCHAR(200),
    amount NUMERIC(12,2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_code VARCHAR(50) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    company VARCHAR(200),
    email VARCHAR(150),
    phone VARCHAR(30),
    source VARCHAR(100),
    status VARCHAR(50) DEFAULT 'new',
    assigned_to VARCHAR(150),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    industry VARCHAR(100),
    requirement VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS customer_equipment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    equipment_code VARCHAR(50) NOT NULL,
    equipment_name VARCHAR(150) NOT NULL,
    equipment_type VARCHAR(100),
    model VARCHAR(150),
    serial_number VARCHAR(150),
    capacity VARCHAR(100),
    installation_date DATE,
    warranty_end_date DATE,
    location VARCHAR(255),
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code VARCHAR(50) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    company VARCHAR(200),
    issue VARCHAR(255),
    priority VARCHAR(50) DEFAULT 'normal',
    status VARCHAR(50) DEFAULT 'open',
    assigned_to VARCHAR(150),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    customer_id INTEGER,
    equipment_id INTEGER
);

CREATE TABLE IF NOT EXISTS amc_contracts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_code VARCHAR(50) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    company VARCHAR(200),
    amount NUMERIC(12,2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'active',
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    customer_id INTEGER,
    equipment_id INTEGER
);

CREATE INDEX IF NOT EXISTS idx_customer_equipment_customer_id
    ON customer_equipment(customer_id);

CREATE INDEX IF NOT EXISTS idx_service_requests_customer_id
    ON service_requests(customer_id);

CREATE INDEX IF NOT EXISTS idx_service_requests_equipment_id
    ON service_requests(equipment_id);

CREATE INDEX IF NOT EXISTS idx_amc_contracts_customer_id
    ON amc_contracts(customer_id);

CREATE INDEX IF NOT EXISTS idx_amc_contracts_equipment_id
    ON amc_contracts(equipment_id);